// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @hypermq/ack
const encoding0 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.consumer)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.consumer)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)

    return {
      consumer: r0
    }
  }
}

// @hypermq/message
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.topic)
    c.buffer.preencode(state, m.data)
    c.uint.preencode(state, m.timestamp)
    c.fixed32.preencode(state, m.key)
    state.end++ // max flag is 2 so always one byte

    if (m.ack) encoding0.preencode(state, m.ack)
    if (m.concurrent) c.uint.preencode(state, m.concurrent)
  },
  encode(state, m) {
    const flags = (m.ack ? 1 : 0) | (m.concurrent ? 2 : 0)

    c.string.encode(state, m.topic)
    c.buffer.encode(state, m.data)
    c.uint.encode(state, m.timestamp)
    c.fixed32.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.ack) encoding0.encode(state, m.ack)
    if (m.concurrent) c.uint.encode(state, m.concurrent)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.fixed32.decode(state)
    const flags = c.uint.decode(state)

    return {
      topic: r0,
      data: r1,
      timestamp: r2,
      key: r3,
      ack: (flags & 1) !== 0 ? encoding0.decode(state) : null,
      concurrent: (flags & 2) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @hypermq/rej-entry
const encoding2 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    c.fixed32.preencode(state, m.consumer)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    c.fixed32.encode(state, m.consumer)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.fixed32.decode(state)

    return {
      key: r0,
      consumer: r1
    }
  }
}

// @hypermq/register-consumer
const encoding3 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)

    return {
      key: r0
    }
  }
}

// @hypermq/ack-entry
const encoding4 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
    encoding0.preencode(state, m.ack)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
    encoding0.encode(state, m.ack)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = encoding0.decode(state)

    return {
      key: r0,
      ack: r1
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@hypermq/ack':
      return encoding0
    case '@hypermq/message':
      return encoding1
    case '@hypermq/rej-entry':
      return encoding2
    case '@hypermq/register-consumer':
      return encoding3
    case '@hypermq/ack-entry':
      return encoding4
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
